name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build-nds:
    name: Build
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build
        run: make

      - name: Archive artifacts
        uses: actions/upload-artifact@v7
        with:
          name: NitroSwan
          path: |
            History.txt
            NitroSwan.nds
            README.md
            WonderWitch.md
